services:
  mongo:
    image: mongo:latest
    container_name: mongo-rs
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    command: ["--replSet", "rs0", "--bind_ip_all"]
    healthcheck:
      test: test $$(echo "rs.status().ok" | mongosh --quiet) -eq 1
      interval: 10s
      timeout: 10s
      retries: 5

volumes:
  mongo-data:
